logging: add missing methods for file-like objects
reason: stopping xivo-websocketd gave:

AttributeError: '_StreamToLogger' object has no attribute 'flush'